# Generated by Django 3.0.5 on 2021-08-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
