# Generated by Django 3.0.5 on 2021-08-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20210806_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='genre',
            field=models.ManyToManyField(blank=True, default=None, related_name='titles', to='api.Genre'),
        ),
    ]
