# Generated by Django 3.0.5 on 2021-08-07 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20210807_1257'),
    ]

    operations = [
        migrations.RenameField(
            model_name='title',
            old_name='published_year',
            new_name='year',
        ),
    ]
